-- ---------------------------------------------------------------------------
-- 1) categories
-- ---------------------------------------------------------------------------
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  name text not null,
  color text not null default '#3b82f6',
  icon text not null default 'Briefcase',
  created_at timestamptz not null default now(),
  unique (user_id, name)
);

create index if not exists categories_user_id_idx on public.categories (user_id);

alter table public.categories enable row level security;

drop policy if exists "Users can select own categories" on public.categories;
create policy "Users can select own categories"
  on public.categories for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own categories" on public.categories;
create policy "Users can insert own categories"
  on public.categories for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own categories" on public.categories;
create policy "Users can update own categories"
  on public.categories for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete own categories" on public.categories;
create policy "Users can delete own categories"
  on public.categories for delete
  using (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- 2) tags
-- ---------------------------------------------------------------------------
create table if not exists public.tags (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  name text not null,
  color text not null default '#64748b',
  created_at timestamptz not null default now(),
  unique (user_id, name)
);

create index if not exists tags_user_id_idx on public.tags (user_id);

alter table public.tags enable row level security;

drop policy if exists "Users can select own tags" on public.tags;
create policy "Users can select own tags"
  on public.tags for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own tags" on public.tags;
create policy "Users can insert own tags"
  on public.tags for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own tags" on public.tags;
create policy "Users can update own tags"
  on public.tags for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete own tags" on public.tags;
create policy "Users can delete own tags"
  on public.tags for delete
  using (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- 3) tasks
-- ---------------------------------------------------------------------------
create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  title text not null,
  description text not null default '',
  done boolean not null default false,
  scheduled timestamptz,
  sort_order int not null default 0,
  category_id bigint references public.categories (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists tasks_user_id_idx on public.tasks (user_id);
create index if not exists tasks_user_done_idx on public.tasks (user_id, done);
create index if not exists tasks_category_id_idx on public.tasks (category_id);

alter table public.tasks enable row level security;

drop policy if exists "Users can select own tasks" on public.tasks;
create policy "Users can select own tasks"
  on public.tasks for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own tasks" on public.tasks;
create policy "Users can insert own tasks"
  on public.tasks for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own tasks" on public.tasks;
create policy "Users can update own tasks"
  on public.tasks for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete own tasks" on public.tasks;
create policy "Users can delete own tasks"
  on public.tasks for delete
  using (auth.uid() = user_id);

create or replace function public.set_tasks_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists tasks_set_updated_at on public.tasks;
create trigger tasks_set_updated_at
  before update on public.tasks
  for each row
  execute function public.set_tasks_updated_at();

-- ---------------------------------------------------------------------------
-- 4) task_tags
-- ---------------------------------------------------------------------------
create table if not exists public.task_tags (
  task_id bigint not null references public.tasks (id) on delete cascade,
  tag_id bigint not null references public.tags (id) on delete cascade,
  primary key (task_id, tag_id)
);

create index if not exists task_tags_tag_id_idx on public.task_tags (tag_id);

alter table public.task_tags enable row level security;

drop policy if exists "Users can select own task_tags" on public.task_tags;
create policy "Users can select own task_tags"
  on public.task_tags for select
  using (
    exists (
      select 1 from public.tasks t
      where t.id = task_id and t.user_id = auth.uid()
    )
  );

drop policy if exists "Users can insert own task_tags" on public.task_tags;
create policy "Users can insert own task_tags"
  on public.task_tags for insert
  with check (
    exists (
      select 1 from public.tasks t
      where t.id = task_id and t.user_id = auth.uid()
    )
    and exists (
      select 1 from public.tags g
      where g.id = tag_id and g.user_id = auth.uid()
    )
  );

drop policy if exists "Users can delete own task_tags" on public.task_tags;
create policy "Users can delete own task_tags"
  on public.task_tags for delete
  using (
    exists (
      select 1 from public.tasks t
      where t.id = task_id and t.user_id = auth.uid()
    )
  );
