-- Pomodoro sessions: one active row per user + finished history.

create table public.pomodoros (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  task_id bigint references public.tasks (id) on delete set null,
  task_name text not null default '',
  duration int not null,
  elapsed bigint not null default 0,
  started_at timestamptz not null default now(),
  paused_at timestamptz,
  ended_at timestamptz,
  created_at timestamptz not null default now()
);

create index pomodoros_user_id_idx on public.pomodoros (user_id);
create index pomodoros_user_ended_idx on public.pomodoros (user_id, ended_at desc nulls first);

-- One in-progress session per user
create unique index pomodoros_one_active_per_user
  on public.pomodoros (user_id)
  where ended_at is null;

alter table public.pomodoros enable row level security;

create policy "Users can select own pomodoros"
  on public.pomodoros for select
  using (auth.uid() = user_id);

create policy "Users can insert own pomodoros"
  on public.pomodoros for insert
  with check (auth.uid() = user_id);

create policy "Users can update own pomodoros"
  on public.pomodoros for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete own pomodoros"
  on public.pomodoros for delete
  using (auth.uid() = user_id);

grant select, insert, update, delete on table public.pomodoros to authenticated;
grant usage, select on all sequences in schema public to authenticated;
